

spring.application.name=learningplatform 


 
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/learningplatform} 
spring.datasource.username=${DB_USERNAME:root} 
spring.datasource.password=${DB_PASSWORD:root} 
 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
 
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} 
jwt.expiration=86400000 
 
judge0.api.url=${JUDGE0_API_URL:https://ce.judge0.com/submissions} 
judge0.api.key=${JUDGE0_API_KEY:} 
 
spring.mail.host=smtp.gmail.com 
spring.mail.port=587 
spring.mail.username=${MAIL_USERNAME} 
spring.mail.password=${MAIL_PASSWORD} 
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true 
 
app.frontend-url=${FRONTEND_URL:http://127.0.0.1:5500} 
app.base-url=${BASE_URL:http://localhost:8080}
