spring.datasource.url=jdbc:mysql://localhost:3306/learningplatform
spring.datasource.username=root
spring.datasource.password=root
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970


BREVO_API_KEY=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

BREVO_SENDER_EMAIL=af2848838@gmail.com


spring.mail.username=
spring.mail.password=bjwh mmro sxaw crpj

app.frontend-url=http://localhost:5173
app.base-url=http://localhost:8080


FRONTEND_URL=http://localhost:5173
