package com.learningplatform.entity;


public enum Permissions
{
	
	STUDENT_READ_ENROLLED_COURSES,
	STUDENT_WRITE_ENROLL_COURSES_BYID,
	STUDENT_READ_MODULES_BY_COURSES,
	STUDENT_READ_QUIZ_QUESTIONS,
	STUDENT_WRITE_SUBMIT_QUIZE,
	STUDENT_READ_PROGRESS,
	STUDENT_READ_ALLCOURSES,
	STUDENT_READ_CODINGPROBLEMS,
	STUDENT_WRITE_SUBMIT_CODE,
	
	
	
	TEACHER_CREATE_COURSE,
	TEACHER_UPDATE_COURSE,
	TEACHER_DELETE_COURSE,
	TEACHER_CREATE_MODULE,
	TEACHER_UPDATE_MODULE,
	TEACHER_CREATE_QUIZ,
	TEACHER_VIEW_STUDENTS,
	TEACHER_CREATE_CODING_PROBLEM

	

}
